//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interop_messages")]
pub struct Model {
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub sender_address_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub target_address_hash: Option<Vec<u8>>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub nonce: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub init_chain_id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub init_transaction_hash: Option<Vec<u8>>,
    pub timestamp: Option<DateTime>,
    pub relay_chain_id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub relay_transaction_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub payload: Option<Vec<u8>>,
    pub failed: Option<bool>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub transfer_token_address_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub transfer_from_address_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub transfer_to_address_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Decimal(Some((78, 0)))", nullable)]
    pub transfer_amount: Option<Decimal>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chains::Entity",
        from = "Column::InitChainId",
        to = "super::chains::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Chains2,
    #[sea_orm(
        belongs_to = "super::chains::Entity",
        from = "Column::RelayChainId",
        to = "super::chains::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Chains1,
}

impl ActiveModelBehavior for ActiveModel {}
