//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::{
    addresses::Entity as Addresses, api_keys::Entity as ApiKeys,
    block_ranges::Entity as BlockRanges, chains::Entity as Chains, dapps::Entity as Dapps,
    hashes::Entity as Hashes, interop_messages::Entity as InteropMessages,
};
