//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "hash_type")]
pub enum HashType {
    #[sea_orm(string_value = "block")]
    Block,
    #[sea_orm(string_value = "transaction")]
    Transaction,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "token_type")]
pub enum TokenType {
    #[sea_orm(string_value = "ERC-1155")]
    Erc1155,
    #[sea_orm(string_value = "ERC-20")]
    Erc20,
    #[sea_orm(string_value = "ERC-404")]
    Erc404,
    #[sea_orm(string_value = "ERC-721")]
    Erc721,
}
