//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::{
    address_notes::Entity as AddressNotes, address_public_tags::Entity as AddressPublicTags,
    address_reputation::Entity as AddressReputation, notes::Entity as Notes,
    public_tags::Entity as PublicTags,
};
