//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "address_tags")]
pub struct Model {
    #[sea_orm(unique)]
    pub id: i32,
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub label: String,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    pub display_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::address_to_tags::Entity")]
    AddressToTags,
}

impl Related<super::address_to_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AddressToTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
