//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "contract_methods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub identifier: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub abi: Json,
    pub r#type: String,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
