//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "market_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub date: Date,
    pub closing_price: Option<BigDecimal>,
    pub opening_price: Option<BigDecimal>,
    pub market_cap: Option<BigDecimal>,
    pub tvl: Option<BigDecimal>,
    pub secondary_coin: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
