//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "entry_point_version"
)]
pub enum EntryPointVersion {
    #[sea_orm(string_value = "v0.6")]
    V06,
    #[sea_orm(string_value = "v0.7")]
    V07,
    #[sea_orm(string_value = "v0.8")]
    V08,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "internal_transactions_call_type"
)]
pub enum InternalTransactionsCallType {
    #[sea_orm(string_value = "call")]
    Call,
    #[sea_orm(string_value = "callcode")]
    Callcode,
    #[sea_orm(string_value = "delegatecall")]
    Delegatecall,
    #[sea_orm(string_value = "staticcall")]
    Staticcall,
    #[sea_orm(string_value = "invalid")]
    Invalid,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "multichain_search_counter_type"
)]
pub enum MultichainSearchCounterType {
    #[sea_orm(string_value = "global")]
    Global,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "multichain_search_hash_type"
)]
pub enum MultichainSearchHashType {
    #[sea_orm(string_value = "block")]
    Block,
    #[sea_orm(string_value = "transaction")]
    Transaction,
    #[sea_orm(string_value = "address")]
    Address,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "multichain_search_token_data_type"
)]
pub enum MultichainSearchTokenDataType {
    #[sea_orm(string_value = "metadata")]
    Metadata,
    #[sea_orm(string_value = "total_supply")]
    TotalSupply,
    #[sea_orm(string_value = "counters")]
    Counters,
    #[sea_orm(string_value = "market_data")]
    MarketData,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "oban_job_state")]
pub enum ObanJobState {
    #[sea_orm(string_value = "available")]
    Available,
    #[sea_orm(string_value = "scheduled")]
    Scheduled,
    #[sea_orm(string_value = "executing")]
    Executing,
    #[sea_orm(string_value = "retryable")]
    Retryable,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "discarded")]
    Discarded,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "proxy_type")]
pub enum ProxyType {
    #[sea_orm(string_value = "eip1167")]
    Eip1167,
    #[sea_orm(string_value = "eip1967")]
    Eip1967,
    #[sea_orm(string_value = "eip1822")]
    Eip1822,
    #[sea_orm(string_value = "eip1967_oz")]
    Eip1967Oz,
    #[sea_orm(string_value = "master_copy")]
    MasterCopy,
    #[sea_orm(string_value = "basic_implementation")]
    BasicImplementation,
    #[sea_orm(string_value = "basic_get_implementation")]
    BasicGetImplementation,
    #[sea_orm(string_value = "comptroller")]
    Comptroller,
    #[sea_orm(string_value = "eip2535")]
    Eip2535,
    #[sea_orm(string_value = "clone_with_immutable_arguments")]
    CloneWithImmutableArguments,
    #[sea_orm(string_value = "eip7702")]
    Eip7702,
    #[sea_orm(string_value = "resolved_delegate_proxy")]
    ResolvedDelegateProxy,
    #[sea_orm(string_value = "erc7760")]
    Erc7760,
    #[sea_orm(string_value = "eip1967_beacon")]
    Eip1967Beacon,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "signed_authorization_status"
)]
pub enum SignedAuthorizationStatus {
    #[sea_orm(string_value = "ok")]
    Ok,
    #[sea_orm(string_value = "invalid_chain_id")]
    InvalidChainId,
    #[sea_orm(string_value = "invalid_signature")]
    InvalidSignature,
    #[sea_orm(string_value = "invalid_nonce")]
    InvalidNonce,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sponsor_type")]
pub enum SponsorType {
    #[sea_orm(string_value = "wallet_deposit")]
    WalletDeposit,
    #[sea_orm(string_value = "wallet_balance")]
    WalletBalance,
    #[sea_orm(string_value = "paymaster_sponsor")]
    PaymasterSponsor,
    #[sea_orm(string_value = "paymaster_hybrid")]
    PaymasterHybrid,
}
