mustache_to_handlebars \
    ~/poa/blockscout-rs/libs/blockscout-client/rust-templates \
    -out_dir ~/poa/blockscout-rs/libs/blockscout-client/rust-templates-handlebars \
    -handlebars_if_tags="
        vendorExtensions.x-group-parameters \
        withAWSV4Signature \
        supportMiddleware \
        reqwestTrait \
        vendorExtensions.x-rust-has-byte-array \
        serdeWith \
        reqwest \
        mockall \
        topLevelApiClient \
        hyper0x \
        oneOf.isEmpty \
        hyper \
        supportAsync \
        supportMultipleResponses \
        isDefault \
        hasFormParams \
        isUuid \
        isFile \
        supportTokenSource \
        is2xx \
        hasBodyParam \
        hasUUIDs \
        isMultipart \
        useBonBuilder \
        hasHeaderParams \
        isModel \
        isResponseFile \
        is3xx \
        is4xx \
        isPrimitiveType \
        isInteger \
        isDeepObject \
        is5xx \
        hasProduces \
        isString \
        hasItems \
        hasHttpSignatureMethods \
        hasAuthMethods \
        isBodyParam \
        isHeaderParam \
        isNullable \
        isKeyInHeader \
        isDouble \
        hasBearerMethods \
        isKeyInQuery \
        isFloat \
        isDateTime \
        hasHttpBasicMethods \
        hasRequiredVars \
        isOAuth \
        isUnboundedInteger \
        isByteArray \
        isCookieParam \
        hasVars \
        getIsNull \
        isEnum \
        isDate \
        isBinary \
        isAnyType \
        isPathParam \
        hasMore \
        isFormParam \
        hasConsumes \
        isNumber \
        getHasRequired \
        isBasic \
        hasApiKeyMethods \
        useNose \
        isHttpSignature \
        hasValidation \
        hasRequired \
        isArray \
        isBasicBearer \
        isAlias \
        isBasicBasic \
        isShort \
        isReadOnly \
        isMap \
        isLong \
        isBoolean \
        hasOAuthMethods \
        isApiKey \
        isQueryParam \
        getHasDiscriminatorWithNonEmptyMapping \
        isKeyInCookie \
        indent \
        complexType \
        produces \
        consumes \
        minItems \
        maxItems \
        getUniqueItems \
        minProperties \
        pattern \
        maxLength \
        exclusiveMinimum \
        maximum \
        multipleOf \
        returnTypeIsPrimitive \
        minLength \
        required \
        additionalPropertiesIsAnyType \
        arrayModelType \
        recursionLimit \
        baseType \
        infoName \
        asyncio \
        tornado \
        additionalPropertiesType \
        infoUrl \
        exclusiveMaximum \
        minimum \
        nameInSnakeCase \
        collectionFormat \
        bearerFormat \
        summary \
        vendorExtensions.x-regex \
        maxProperties" \
    -handlebars_each_tags="
        allParams \
        responses \
        headerParams \
        servers \
        scopes \
        vendorExtensions.x-auth-id-alias \
        getComposedSchemas \
        enumVars \
        optionalParams \
        optionalVars \
        headers \
        imports \
        mappedModels \
        requiredVars \
        vars \
        models \
        apis \
        authMethods \
        requiredParams \
        enumValues \
        vendorExtensions \
        formParams \
        x-mapped-models \
        queryParams \
        bodyParams \
        uniqueItems \
        pathParams" \
    -handlebars_with_tags="
        appName \
        infoEmail \
        homePageUrl \
        composedSchemas.oneOf \
        lambdaVersion \
        allParams.[0] \
        publishRustRegistry \
        repositoryUrl \
        baseName \
        lambda.lifetimeName \
        documentationUrl \
        items \
        additionalProperties \
        model \
        apiInfo \
        operations \
        allowableValues \
        appDescription \
        appDescriptionWithNewLines \
        licenseInfo \
        discriminator \
        description \
        returnType \
        defaultValue \
        version \
        httpUserAgent \
        notes \
        operation \
        oneOf"