port := "3030"
transaction_hash := "0x388C818CA8B9251b393131C08a736A67ccB19297"
block_number_or_hash := "20076838"
address_hash := "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
id := "0"

base_url := "https://eth.blockscout.com"
proxy := "--proxy http://localhost:3030"

init:
    cargo install stubr-cli

record:
    stubr record -p {{port}}


