//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use super::sea_orm_active_enums::StatusEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interval")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub start: DateTime,
    pub finish: DateTime,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    pub status: StatusEnum,
    pub next_retry: Option<DateTime>,
    pub retry_count: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
