//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "operation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub operation_id: i32,
    pub timestamp: i64,
    pub next_retry: Option<i64>,
    pub status: i16,
    pub retry_count: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::operation_stage::Entity")]
    Operation,
}

impl Related<super::operation_stage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Operation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
