//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::{
    interval::Entity as Interval, operation::Entity as Operation,
    operation_stage::Entity as OperationStage, stage_type::Entity as StageType,
    transaction::Entity as Transaction, watermark::Entity as Watermark,
};
