//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use super::sea_orm_active_enums::BridgeType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bridges")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    pub r#type: Option<BridgeType>,
    pub enabled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ui_url: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bridge_contracts::Entity")]
    BridgeContracts,
    #[sea_orm(has_many = "super::bridge_txs::Entity")]
    BridgeTxs,
    #[sea_orm(has_many = "super::crosschain_messages::Entity")]
    CrosschainMessages,
    #[sea_orm(has_many = "super::indexer_checkpoints::Entity")]
    IndexerCheckpoints,
    #[sea_orm(has_many = "super::indexer_failures::Entity")]
    IndexerFailures,
}

impl Related<super::bridge_contracts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BridgeContracts.def()
    }
}

impl Related<super::bridge_txs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BridgeTxs.def()
    }
}

impl Related<super::crosschain_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrosschainMessages.def()
    }
}

impl Related<super::indexer_checkpoints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IndexerCheckpoints.def()
    }
}

impl Related<super::indexer_failures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IndexerFailures.def()
    }
}

impl Related<super::chains::Entity> for Entity {
    fn to() -> RelationDef {
        super::indexer_checkpoints::Relation::Chains.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::indexer_checkpoints::Relation::Bridges.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
