//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bridge_contracts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub bridge_id: i32,
    pub chain_id: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub address: Vec<u8>,
    pub version: i16,
    pub abi: Option<Json>,
    pub started_at_block: Option<i64>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bridge_txs::Entity")]
    BridgeTxs,
    #[sea_orm(
        belongs_to = "super::bridges::Entity",
        from = "Column::BridgeId",
        to = "super::bridges::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Bridges,
    #[sea_orm(
        belongs_to = "super::chains::Entity",
        from = "Column::ChainId",
        to = "super::chains::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Chains,
}

impl Related<super::bridge_txs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BridgeTxs.def()
    }
}

impl Related<super::bridges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bridges.def()
    }
}

impl Related<super::chains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chains.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
