//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::{
    avalanche_icm_blockchain_ids::Entity as AvalancheIcmBlockchainIds,
    bridge_contracts::Entity as BridgeContracts, bridges::Entity as Bridges,
    chains::Entity as Chains, crosschain_messages::Entity as CrosschainMessages,
    crosschain_transfers::Entity as CrosschainTransfers,
    indexer_checkpoints::Entity as IndexerCheckpoints, indexer_failures::Entity as IndexerFailures,
    pending_messages::Entity as PendingMessages, tokens::Entity as Tokens,
};
