//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::{
    amb_message_anomalies::Entity as AmbMessageAnomalies,
    amb_messages_confirmations::Entity as AmbMessagesConfirmations,
    avalanche_icm_blockchain_ids::Entity as AvalancheIcmBlockchainIds,
    bridge_contracts::Entity as BridgeContracts, bridges::Entity as Bridges,
    chains::Entity as Chains, crosschain_messages::Entity as CrosschainMessages,
    crosschain_transfers::Entity as CrosschainTransfers,
    indexer_checkpoints::Entity as IndexerCheckpoints, indexer_failures::Entity as IndexerFailures,
    pending_messages::Entity as PendingMessages, stats_asset_edges::Entity as StatsAssetEdges,
    stats_asset_tokens::Entity as StatsAssetTokens, stats_assets::Entity as StatsAssets,
    stats_chains::Entity as StatsChains, stats_messages::Entity as StatsMessages,
    stats_messages_days::Entity as StatsMessagesDays, tokens::Entity as Tokens,
};
