//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::EdgeDecimalsSide;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stats_asset_edges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub stats_asset_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub src_chain_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dst_chain_id: i64,
    pub transfers_count: i64,
    #[sea_orm(column_type = "Decimal(Some((78, 0)))")]
    pub cumulative_amount: BigDecimal,
    pub decimals: Option<i16>,
    pub decimals_side: EdgeDecimalsSide,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chains::Entity",
        from = "Column::DstChainId",
        to = "super::chains::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chains2,
    #[sea_orm(
        belongs_to = "super::chains::Entity",
        from = "Column::SrcChainId",
        to = "super::chains::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chains1,
    #[sea_orm(
        belongs_to = "super::stats_assets::Entity",
        from = "Column::StatsAssetId",
        to = "super::stats_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StatsAssets,
}

impl Related<super::stats_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatsAssets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
