//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stats_assets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub symbol: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon_url: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::crosschain_transfers::Entity")]
    CrosschainTransfers,
    #[sea_orm(has_many = "super::stats_asset_edges::Entity")]
    StatsAssetEdges,
    #[sea_orm(has_many = "super::stats_asset_tokens::Entity")]
    StatsAssetTokens,
}

impl Related<super::crosschain_transfers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrosschainTransfers.def()
    }
}

impl Related<super::stats_asset_edges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatsAssetEdges.def()
    }
}

impl Related<super::stats_asset_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatsAssetTokens.def()
    }
}

impl Related<super::chains::Entity> for Entity {
    fn to() -> RelationDef {
        super::stats_asset_tokens::Relation::Chains.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::stats_asset_tokens::Relation::StatsAssets.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
