//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stats_messages_days")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: Date,
    #[sea_orm(primary_key, auto_increment = false)]
    pub src_chain_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dst_chain_id: i64,
    pub messages_count: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chains::Entity",
        from = "Column::DstChainId",
        to = "super::chains::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chains2,
    #[sea_orm(
        belongs_to = "super::chains::Entity",
        from = "Column::SrcChainId",
        to = "super::chains::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chains1,
}

impl ActiveModelBehavior for ActiveModel {}
