//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    code::Entity as Code, compiled_contracts::Entity as CompiledContracts,
    contract_deployments::Entity as ContractDeployments, contracts::Entity as Contracts,
    verified_contracts::Entity as VerifiedContracts,
};
