//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "verified_contracts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub compilation_id: Uuid,
    pub contract_id: Uuid,
    pub creation_match: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub creation_values: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub creation_transformations: Option<Json>,
    pub runtime_match: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub runtime_values: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub runtime_transformations: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::compiled_contracts::Entity",
        from = "Column::CompilationId",
        to = "super::compiled_contracts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CompiledContracts,
    #[sea_orm(
        belongs_to = "super::contracts::Entity",
        from = "Column::ContractId",
        to = "super::contracts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Contracts,
}

impl Related<super::compiled_contracts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompiledContracts.def()
    }
}

impl Related<super::contracts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contracts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
