DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS block_ranges;
DROP TABLE IF EXISTS dapps;
DROP TABLE IF EXISTS hashes;
DROP TABLE IF EXISTS chains;

DROP TYPE IF EXISTS token_type;
DROP TYPE IF EXISTS hash_type;

DROP EXTENSION IF EXISTS pg_trgm;
