use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let sql = r#"
        CREATE TABLE api_keys (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            key UUID NOT NULL UNIQUE,
            chain_id bigint NOT NULL REFERENCES chains (id),
            created_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
        );
        "#;
        crate::from_sql(manager, sql).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let sql = r#"
        DROP TABLE api_keys;
        "#;
        crate::from_sql(manager, sql).await?;
        Ok(())
    }
}
