//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::{
    bytecode_types::Entity as BytecodeTypes, failures::Entity as Failures,
    pending_addresses::Entity as PendingAddresses, pending_tasks::Entity as PendingTasks,
    verified_contracts::Entity as VerifiedContracts,
};
