//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    cctx_status::Entity as CctxStatus, cross_chain_tx::Entity as CrossChainTx,
    inbound_params::Entity as InboundParams, outbound_params::Entity as OutboundParams,
    revert_options::Entity as RevertOptions, token::Entity as Token,
    watermark::Entity as Watermark,
};
