//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub name: String,
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::source_files::Entity")]
    SourceFiles,
}

impl Related<super::source_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourceFiles.def()
    }
}

impl Related<super::sources::Entity> for Entity {
    fn to() -> RelationDef {
        super::source_files::Relation::Sources.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::source_files::Relation::Files.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
