//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "chart_data_double")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub chart_id: i32,
    pub date: Date,
    pub value: f64,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::charts::Entity",
        from = "Column::ChartId",
        to = "super::charts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Charts,
}

impl Related<super::charts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Charts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
