//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "native_coin_supply_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub address: Vec<u8>,
    #[sea_orm(column_type = "Decimal(Some((100, 0)))")]
    pub balance: Decimal,
    pub date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
