//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::{
    chart_data_double::Entity as ChartDataDouble, chart_data_int::Entity as ChartDataInt,
    charts::Entity as Charts, kv_storage::Entity as KvStorage,
};
