//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "balance_changes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub changed_by_user_id: Option<i32>,
    pub amount: Decimal,
    pub created_at: DateTimeWithTimeZone,
    pub note: Option<String>,
    pub register_promo_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::register_promo::Entity",
        from = "Column::RegisterPromoId",
        to = "super::register_promo::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    RegisterPromo,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ChangedByUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
}

impl Related<super::register_promo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegisterPromo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
