type: google.api.Service
config_version: 3

http:
  rules:
    - selector: blockscout.tacOperationLifecycle.v1.TacService.GetOperations
      get: /api/v1/tac/operations
    - selector: blockscout.tacOperationLifecycle.v1.TacService.GetOperationDetails
      get: /api/v1/tac/operations/{operation_id}
    - selector: blockscout.tacOperationLifecycle.v1.TacService.GetOperationsByTransaction
      get: /api/v1/tac/operations:byTx/{tx_hash}
    - selector: blockscout.tacOperationLifecycle.v2.TacServiceV2.GetOperations
      get: /api/v2/tac/operations
    - selector: blockscout.tacOperationLifecycle.v2.TacServiceV2.GetOperationDetails
      get: /api/v2/tac/operations/{operation_id}
    - selector: blockscout.tacOperationLifecycle.v2.TacServiceV2.GetOperationsByTransaction
      get: /api/v2/tac/operations:byTx/{tx_hash}
    - selector: blockscout.tacOperationLifecycle.v1.TacStatistic.GetFullStatistics
      get: /api/v1/stat/full
    - selector: blockscout.tacOperationLifecycle.v1.TacStatistic.GetIntervalStatistics
      get: /api/v1/stat/intervals
    - selector: blockscout.tacOperationLifecycle.v1.TacStatistic.GetOperationStatistics
      get: /api/v1/stat/operations
    - selector: blockscout.tacOperationLifecycle.v1.Health.Check
      get: /health
