/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use derive_new::new;
use serde::{Deserialize, Serialize};

#[derive(new, Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressParam {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "implementation_name")]
    pub implementation_name: Option<String>,
    #[serde(rename = "name")]
    pub name: Option<String>,
    #[serde(rename = "is_contract")]
    pub is_contract: bool,
    #[serde(rename = "private_tags")]
    pub private_tags: Vec<models::AddressTag>,
    #[serde(rename = "watchlist_names")]
    pub watchlist_names: Vec<models::WatchlistName>,
    #[serde(rename = "public_tags")]
    pub public_tags: Vec<models::AddressTag>,
    #[serde(rename = "is_verified")]
    pub is_verified: Option<bool>,
}
