/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct AddressWithTxCount {
    // isNullable = false
    // required = false
    
    pub creator_address_hash: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub creation_transaction_hash: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub token: 
    Option<


            
            models::TokenInfo
            

    >,
    // isNullable = false
    // required = false
    
    pub coin_balance: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub exchange_rate: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub implementation_address: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    pub block_number_balance_updated_at: 
    Option<


            
            i32

    >,
    // isNullable = false
    // required = true
    
    pub hash: 
    


            
            String

    ,
    // isNullable = false
    // required = false
    
    pub implementation_name: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub name: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub is_contract: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub private_tags: 
    Option<


            
            Vec<models::AddressTag>

    >,
    // isNullable = false
    // required = false
    
    pub watchlist_names: 
    Option<


            
            Vec<models::WatchlistName>

    >,
    // isNullable = false
    // required = false
    
    pub public_tags: 
    Option<


            
            Vec<models::AddressTag>

    >,
    // isNullable = false
    // required = false
    
    pub is_verified: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub has_beacon_chain_withdrawals: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub has_logs: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub has_token_transfers: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub has_tokens: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub has_validated_blocks: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = true
    
    pub transaction_count: 
    


            
            String

    ,
}



