/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct AddressNftInstance {
    #[serde(default)]
    pub is_unique: Option<bool>,

    pub id: String,
    #[serde(default)]
    pub holder_address_hash: Option<String>,

    #[serde(default)]
    pub image_url: Option<String>,

    #[serde(default)]
    pub animation_url: Option<String>,

    #[serde(default)]
    pub external_app_url: Option<String>,

    #[serde(default)]
    pub metadata: Option<serde_json::Value>,

    #[serde(default)]
    pub owner: Option<models::AddressParam>,

    #[serde(default)]
    pub token: Option<models::TokenInfo>,

    pub token_type: String,
    #[serde(default)]
    pub value: Option<String>,
}
