/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct AddressParam {
    pub hash: String,
    #[serde(default)]
    pub implementation_name: Option<String>,

    #[serde(default)]
    pub name: Option<String>,

    #[serde(default)]
    pub ens_domain_name: Option<String>,

    #[serde(default)]
    pub metadata: Option<serde_json::Value>,

    pub is_contract: bool,
    pub private_tags: Vec<models::AddressTag>,
    pub watchlist_names: Vec<models::WatchlistName>,
    pub public_tags: Vec<models::AddressTag>,
    #[serde(default)]
    pub is_verified: Option<bool>,
}
