/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;














#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct Block {

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub base_fee_per_gas: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub burnt_fees: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub burnt_fees_percentage: 
    
    

    
    

    
    
        
        
            
            f64
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub difficulty: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = true
    // required = true
    
    
    
    
    
    
    pub extra_data: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub gas_limit: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub gas_target_percentage: 
    
    

    
    

    
    
        
        
            
            f64
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub gas_used: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub gas_used_percentage: 
    
    

    
    

    
    
        
        
            
            f64
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub hash: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    
    #[serde(deserialize_with = "deserialize_number_from_string")]
    
    
    
    
    
    
    pub height: 
    
    

    
    

    
    
        
        
            
            i32
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub miner: 
    
    

    
    

    
    
        
            
            models::AddressParam
            
        
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub nonce: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub parent_hash: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub priority_fee: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub rewards: 
    
    

    
    

    
    
        
        
            
            Vec<models::Reward>
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    
    #[serde(deserialize_with = "deserialize_number_from_string")]
    
    
    
    
    
    
    pub size: 
    
    

    
    

    
    
        
        
            
            i32
        
    

    
    ,

    
    // isNullable = true
    // required = true
    
    
    
    
    
    
    pub state_root: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub timestamp: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub total_difficulty: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    
    #[serde(deserialize_with = "deserialize_number_from_string")]
    
    
    
    
    
    
    pub transaction_count: 
    
    

    
    

    
    
        
        
            
            i32
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub transaction_fees: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub r#type: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub uncles_hashes: 
    
    

    
    

    
    
        
        
            
            Vec<String>
        
    

    
    ,

    
    // isNullable = true
    // required = true
    
    
    
    
    
    
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    
    
    
    
    
    
    pub withdrawals_count: 
    
    Option<

    
    

    
    
        
        
            
            i32
        
    

    
    >,

}





























































