/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtendedRevertReasonAsMap {
    #[serde(rename = "raw")]
    pub raw: String,
    #[serde(rename = "code")]
    pub code: i32,
    #[serde(rename = "message")]
    pub message: String,
}

impl ExtendedRevertReasonAsMap {
    pub fn new(raw: String, code: i32, message: String) -> ExtendedRevertReasonAsMap {
        ExtendedRevertReasonAsMap { raw, code, message }
    }
}
