/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSmartContractsCounters200Response {
    #[serde(rename = "new_smart_contracts_24h")]
    pub new_smart_contracts_24h: String,
    #[serde(rename = "new_verified_smart_contracts_24h")]
    pub new_verified_smart_contracts_24h: String,
    #[serde(rename = "smart_contracts")]
    pub smart_contracts: String,
    #[serde(rename = "verified_smart_contracts")]
    pub verified_smart_contracts: String,
}

impl GetSmartContractsCounters200Response {
    pub fn new(
        new_smart_contracts_24h: String,
        new_verified_smart_contracts_24h: String,
        smart_contracts: String,
        verified_smart_contracts: String,
    ) -> GetSmartContractsCounters200Response {
        GetSmartContractsCounters200Response {
            new_smart_contracts_24h,
            new_verified_smart_contracts_24h,
            smart_contracts,
            verified_smart_contracts,
        }
    }
}
