/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct GetSmartContractsCounters200Response {
    pub new_smart_contracts_24h: String,
    pub new_verified_smart_contracts_24h: String,
    pub smart_contracts: String,
    pub verified_smart_contracts: String,
}
