/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct Holder {
    // isNullable = false
    // required = true
    
    pub address: 
    


            
            models::AddressParam
            

    ,
    // isNullable = false
    // required = true
    
    pub value: 
    


            
            String

    ,
    // isNullable = false
    // required = false
    
    pub token_id: 
    Option<


            
            String

    >,
}



