/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct InternalTransaction {
    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub block_number: i32,
    #[serde(default)]
    pub created_contract: Option<models::AddressParam>,

    #[serde(default)]
    pub error: Option<String>,

    pub from: models::AddressParam,
    pub gas_limit: String,
    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub index: i32,
    pub success: bool,
    pub timestamp: String,
    pub to: models::AddressParam,
    pub transaction_hash: String,
    pub r#type: String,
    pub value: String,
}
