/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;














#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct Log {

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub address: 
    
    

    
    

    
    
        
            
            models::AddressParam
            
        
        
    

    
    ,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub block_hash: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    
    
    
    
    
    
    pub block_number: 
    
    Option<

    
    

    
    
        
        
            
            i32
        
    

    
    >,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub data: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub decoded: 
    
    

    
    

    
    
        
            
            models::DecodedInputLog
            
        
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    
    #[serde(deserialize_with = "deserialize_number_from_string")]
    
    
    
    
    
    
    pub index: 
    
    

    
    

    
    
        
        
            
            i32
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub smart_contract: 
    
    

    
    

    
    
        
            
            models::AddressParam
            
        
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub topics: 
    
    

    
    

    
    
        
        
            
            Vec<String>
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub transaction_hash: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

}





























