/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NftChange {
    #[serde(rename = "direction")]
    pub direction: String,
    #[serde(rename = "total")]
    pub total: models::TotalErc721,
}

impl NftChange {
    pub fn new(direction: String, total: models::TotalErc721) -> NftChange {
        NftChange { direction, total }
    }
}
