/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;














#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct RawTrace {

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub action: 
    
    

    
    

    
    
        
            
            models::RawTraceAction
            
        
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    
    #[serde(deserialize_with = "deserialize_number_from_string")]
    
    
    
    
    
    
    pub subtraces: 
    
    

    
    

    
    
        
        
            
            i32
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub trace_address: 
    
    

    
    

    
    
        
        
            
            Vec<i32>
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub r#type: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub error: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub result: 
    
    Option<

    
    

    
    
        
            
            models::RawTraceResult
            
        
        
    

    
    >,

}























