/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RawTraceSelfDestructAction {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "balance")]
    pub balance: String,
    #[serde(rename = "refundAddress")]
    pub refund_address: String,
}

impl RawTraceSelfDestructAction {
    pub fn new(
        address: String,
        balance: String,
        refund_address: String,
    ) -> RawTraceSelfDestructAction {
        RawTraceSelfDestructAction {
            address,
            balance,
            refund_address,
        }
    }
}
