/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct RawTrace {
    pub action: models::RawTraceAction,
    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub subtraces: i32,
    pub trace_address: Vec<i32>,
    pub r#type: String,
    #[serde(default)]
    pub error: Option<String>,

    #[serde(default)]
    pub result: Option<models::RawTraceResult>,
}
