/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecaptchaBody {
    #[serde(rename = "recaptcha_response")]
    pub recaptcha_response: String,
}

impl RecaptchaBody {
    pub fn new(recaptcha_response: String) -> RecaptchaBody {
        RecaptchaBody { recaptcha_response }
    }
}
