/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;














#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct RefetchTokenInstanceMetadata403Response {

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub message: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

}













