/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct RpcStatus {
    // true false false true
    #[serde(deserialize_with = "deserialize_option_number_from_string")]
    #[serde(default)]
    pub code: Option<i32>,

    #[serde(default)]
    pub message: Option<String>,

    #[serde(default)]
    pub details: Option<Vec<models::ProtobufAny>>,
}
