/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;


















#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Search200ResponseItemsInner {

    
    search_200_response_items_inner(oneOf<SearchResultToken,SearchResultAddressOrContract,SearchResultBlock,SearchResultTransaction>),

}

impl Default for Search200ResponseItemsInner {
    fn default() -> Self {
        Self::search_200_response_items_inner(Default::default())
    }
}








































