/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;














#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct SmartContract {

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub verified_twin_address_hash: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub is_verified: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub is_changed_bytecode: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub is_partially_verified: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub is_fully_verified: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub is_verified_via_sourcify: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub is_verified_via_eth_bytecode_db: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub is_self_destructed: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub can_be_visualized_via_sol2uml: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub minimal_proxy_address_hash: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub sourcify_repo_url: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub name: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub optimization_enabled: 
    
    Option<

    
    

    
    
        
        
            
            bool
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    
    
    
    
    
    
    pub optimizations_runs: 
    
    Option<

    
    

    
    
        
        
            
            i32
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub compiler_version: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub evm_version: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub verified_at: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = true
    // required = false
    
    
    
    
    
    
    pub abi: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub source_code: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub file_path: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub compiler_settings: 
    
    Option<

    
    

    
    
        
        
            
            serde_json::Value
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub constructor_args: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub additional_sources: 
    
    Option<

    
    

    
    
        
        
            
            Vec<models::ContractSource>
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub decoded_constructor_args: 
    
    Option<

    
    

    
    
        
        
            
            Vec<serde_json::Value>
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub deployed_bytecode: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub creation_bytecode: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub external_libraries: 
    
    Option<

    
    

    
    
        
        
            
            Vec<models::ExternalLibrary>
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub language: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub status: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

}





































































