/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;














#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct SmartContractForList {

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub address: 
    
    

    
    

    
    
        
            
            models::AddressParam
            
        
        
    

    
    ,

    
    // isNullable = true
    // required = true
    
    
    
    
    
    
    pub coin_balance: 
    
    Option<

    
    

    
    
        
        
            
            String
        
    

    
    >,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub compiler_version: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub language: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub has_constructor_args: 
    
    

    
    

    
    
        
        
            
            bool
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub optimization_enabled: 
    
    

    
    

    
    
        
        
            
            bool
        
    

    
    ,

    
    // isNullable = true
    // required = false
    
    
    
    
    
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    
    
    
    
    
    
    
    pub transaction_count: 
    
    Option<

    
    

    
    
        
        
            
            i32
        
    

    
    >,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub verified_at: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = true
    // required = false
    
    
    
    
    
    
    pub market_cap: 
    
    Option<

    
    

    
    
        
        
            
            f64
        
    

    
    >,

}





























