/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct SmartContractForList {
    pub address: models::AddressParam,
    #[serde(default)]
    pub coin_balance: Option<String>,

    pub compiler_version: String,
    pub language: String,
    pub has_constructor_args: bool,
    pub optimization_enabled: bool,
    // true false false true
    #[serde(deserialize_with = "deserialize_option_number_from_string")]
    #[serde(default)]
    pub transaction_count: Option<i32>,

    pub verified_at: String,
    // false false true true
    #[serde(deserialize_with = "deserialize_option_number_from_string")]
    #[serde(default)]
    pub market_cap: Option<f64>,
}
