/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsResponse {
    #[serde(rename = "total_blocks")]
    pub total_blocks: String,
    #[serde(rename = "total_addresses")]
    pub total_addresses: String,
    #[serde(rename = "total_transactions")]
    pub total_transactions: String,
    #[serde(rename = "average_block_time")]
    pub average_block_time: f64,
    #[serde(rename = "coin_price")]
    pub coin_price: String,
    #[serde(rename = "total_gas_used")]
    pub total_gas_used: String,
    #[serde(rename = "transactions_today")]
    pub transactions_today: String,
    #[serde(rename = "gas_used_today")]
    pub gas_used_today: String,
    #[serde(rename = "gas_prices")]
    pub gas_prices: serde_json::Value,
    #[serde(rename = "static_gas_price")]
    pub static_gas_price: String,
    #[serde(rename = "market_cap")]
    pub market_cap: String,
    #[serde(rename = "network_utilization_percentage")]
    pub network_utilization_percentage: f64,
}

impl StatsResponse {
    pub fn new(
        total_blocks: String,
        total_addresses: String,
        total_transactions: String,
        average_block_time: f64,
        coin_price: String,
        total_gas_used: String,
        transactions_today: String,
        gas_used_today: String,
        gas_prices: serde_json::Value,
        static_gas_price: String,
        market_cap: String,
        network_utilization_percentage: f64,
    ) -> StatsResponse {
        StatsResponse {
            total_blocks,
            total_addresses,
            total_transactions,
            average_block_time,
            coin_price,
            total_gas_used,
            transactions_today,
            gas_used_today,
            gas_prices,
            static_gas_price,
            market_cap,
            network_utilization_percentage,
        }
    }
}
