/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct StateChange {
    // isNullable = false
    // required = false
    
    pub token: 
    Option<


            
            models::TokenInfo
            

    >,
    // isNullable = false
    // required = true
    
    pub r#type: 
    


            
            String

    ,
    // isNullable = false
    // required = true
    
    pub is_miner: 
    


            
            bool

    ,
    // isNullable = false
    // required = true
    
    pub address: 
    


            
            models::AddressParam
            

    ,
    // isNullable = false
    // required = false
    
    pub balance_before: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub balance_after: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub token_id: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub change: 
    Option<


            
            models::StateChangeChange
            

    >,
}



