/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;














#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct Summary {

    
    /// CodegenProperty{openApiType='string', baseName='summary_template', complexType='null', getter='getSummaryTemplate', setter='setSummaryTemplate', description='Summary template', dataType='String', datatypeWithEnum='String', dataFormat='null', name='summary_template', min='null', max='null', defaultValue='null', defaultValueWithParam=' = data.summary_template;', baseType='String', containerType='null', containerTypeMapped='null', title='null', unescapedDescription='Summary template', maxLength=null, minLength=null, pattern='null', example='{action_type} of {amount} {token}', jsonSchema='{
  "description" : "Summary template",
  "example" : "{action_type} of {amount} {token}",
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=true, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isPassword=false, isFreeFormObject=false, isArray=false, isMap=false, isOptional=false, isEnum=false, isInnerEnum=false, isEnumRef=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, isNew=false, isOverridden=null, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='summaryTemplate', nameInPascalCase='SummaryTemplate', nameInSnakeCase='SUMMARY_TEMPLATE', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, uniqueItemsBoolean=null, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, isVoid=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false, hasSanitizedName=false, requiredVarsMap=null, ref=null, schemaIsFromAdditionalProperties=false, isBooleanSchemaTrue=false, isBooleanSchemaFalse=false, format=null, dependentRequired=null, contains=null}
    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub summary_template: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub summary_template_variables: 
    
    

    
    

    
    
        
            
            models::SummaryTemplateVariables
            
        
        
    

    
    ,

}















