/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;














#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct TokenBalance {

    
    // isNullable = false
    // required = false
    
    
    
    
    
    
    pub token_instance: 
    
    Option<

    
    

    
    
        
            
            models::NftInstance
            
        
        
    

    
    >,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub value: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub token_id: 
    
    

    
    

    
    
        
        
            
            String
        
    

    
    ,

    
    // isNullable = false
    // required = true
    
    
    
    
    
    
    pub token: 
    
    

    
    

    
    
        
            
            models::Token
            
        
        
    

    
    ,

}



















