/*
 
 * BlockScout API
 *
 
 
 * API for BlockScout web app
 *
 
 * The version of the OpenAPI document: {size=54, empty=false}
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;


















#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TokenTransferTotal {

    
    TokenTransfer_total(oneOf<TotalERC20,TotalERC721,TotalERC1155>),

}

impl Default for TokenTransferTotal {
    fn default() -> Self {
        Self::TokenTransfer_total(Default::default())
    }
}
















