/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct TokenBalance {
    #[serde(default)]
    pub token_instance: Option<models::NftInstance>,

    #[serde(default)]
    pub value: Option<String>,

    #[serde(default)]
    pub token_id: Option<String>,

    #[serde(default)]
    pub token: Option<models::Token>,
}
