/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct TokenInfoDetailed {
    /// Token Address
    pub address: String,
    /// Token circulating market cap

    #[serde(deserialize_with = "deserialize_option_number_from_string")]
    #[serde(default)]
    pub circulating_market_cap: Option<f64>,

    /// Token decimals

    #[serde(deserialize_with = "deserialize_option_number_from_string")]
    #[serde(default)]
    pub decimals: Option<i64>,

    /// Token exchange rate

    #[serde(default)]
    pub exchange_rate: Option<String>,

    /// Token holders amount

    #[serde(deserialize_with = "deserialize_option_number_from_string")]
    #[serde(default)]
    pub holders: Option<i64>,

    /// Token image URL

    #[serde(default)]
    pub icon_url: Option<String>,

    /// Token name

    #[serde(default)]
    pub name: Option<String>,

    /// Token symbol

    #[serde(default)]
    pub symbol: Option<String>,

    /// Token total supply

    #[serde(default)]
    pub total_supply: Option<String>,

    /// Token type

    #[serde(default)]
    pub r#type: Option<String>,

    /// Token trading volume for past 24h

    #[serde(deserialize_with = "deserialize_option_number_from_string")]
    #[serde(default)]
    pub volume_24h: Option<f64>,
}
