/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(derive_new::new, Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenTransfer {
    #[serde(rename = "block_hash")]
    pub block_hash: String,
    #[serde(rename = "from")]
    pub from: models::AddressParam,
    #[serde(rename = "log_index")]
    pub log_index: i32, // changed
    #[serde(rename = "method")]
    pub method: Option<String>, // changed
    #[serde(rename = "timestamp")]
    pub timestamp: Option<String>, // changed
    #[serde(rename = "to")]
    pub to: models::AddressParam,
    #[serde(rename = "token")]
    pub token: models::TokenInfo,
    #[serde(rename = "total")]
    pub total: models::TokenTransferTotal,
    #[serde(rename = "transaction_hash")]
    pub transaction_hash: String,
    #[serde(rename = "type")]
    pub r#type: String,
}
