/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenBalance {
    #[serde(rename = "token_instance", skip_serializing_if = "Option::is_none")]
    pub token_instance: Option<models::NftInstance>,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "token_id")]
    pub token_id: String,
    #[serde(rename = "token")]
    pub token: models::Token,
}

impl TokenBalance {
    pub fn new(value: String, token_id: String, token: models::Token) -> TokenBalance {
        TokenBalance {
            token_instance: None,
            value,
            token_id,
            token,
        }
    }
}
