/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenInfo {
    #[serde(rename = "circulating_market_cap")]
    pub circulating_market_cap: String,
    #[serde(rename = "icon_url")]
    pub icon_url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "decimals")]
    pub decimals: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "holders")]
    pub holders: String,
    #[serde(rename = "exchange_rate")]
    pub exchange_rate: String,
    #[serde(rename = "total_supply")]
    pub total_supply: String,
}

impl TokenInfo {
    pub fn new(
        circulating_market_cap: String,
        icon_url: String,
        name: String,
        decimals: String,
        symbol: String,
        address: String,
        r#type: String,
        holders: String,
        exchange_rate: String,
        total_supply: String,
    ) -> TokenInfo {
        TokenInfo {
            circulating_market_cap,
            icon_url,
            name,
            decimals,
            symbol,
            address,
            r#type,
            holders,
            exchange_rate,
            total_supply,
        }
    }
}
