/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct TokenAddressParam {
    // isNullable = false
    // required = true
    
    pub hash: 
    


            
            String

    ,
    // isNullable = false
    // required = true
    
    pub implementation_name: 
    


            
            String

    ,
    // isNullable = false
    // required = true
    
    pub name: 
    


            
            String

    ,
    // isNullable = false
    // required = true
    
    pub is_contract: 
    


            
            bool

    ,
    // isNullable = false
    // required = true
    
    pub is_verified: 
    


            
            bool

    ,
    // isNullable = false
    // required = true
    
    pub private_tags: 
    


            
            Vec<models::AddressTag>

    ,
    // isNullable = false
    // required = true
    
    pub public_tags: 
    


            
            Vec<models::AddressTag>

    ,
    // isNullable = false
    // required = true
    
    pub watchlist_names: 
    


            
            Vec<models::WatchlistName>

    ,
    /// Address
    // isNullable = false
    // required = false
    
    pub address: 
    Option<


            
            String

    >,
}



