/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotalErc20 {
    #[serde(rename = "decimals")]
    pub decimals: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl TotalErc20 {
    pub fn new(decimals: String, value: String) -> TotalErc20 {
        TotalErc20 { decimals, value }
    }
}
