/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotalErc721 {
    #[serde(rename = "token_id")]
    pub token_id: String,
}

impl TotalErc721 {
    pub fn new(token_id: String) -> TotalErc721 {
        TotalErc721 { token_id }
    }
}
