/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct Transaction {
    pub timestamp: String,
    pub fee: models::Fee,
    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub gas_limit: i32,
    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub block_number: i32,
    pub status: String,
    #[serde(default)]
    pub method: Option<String>,

    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub confirmations: i32,
    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub r#type: i32,
    pub exchange_rate: String,
    pub to: models::AddressParam,
    #[serde(default)]
    pub transaction_burnt_fee: Option<String>,

    #[serde(default)]
    pub max_fee_per_gas: Option<String>,

    pub result: String,
    pub hash: String,
    pub gas_price: String,
    #[serde(default)]
    pub priority_fee: Option<String>,

    pub base_fee_per_gas: String,
    pub from: models::AddressParam,
    #[serde(default)]
    pub token_transfers: Option<Vec<models::TokenTransfer>>,

    pub transaction_types: Vec<String>,
    pub gas_used: String,
    #[serde(default)]
    pub created_contract: Option<models::AddressParam>,

    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub position: i32,
    #[serde(deserialize_with = "deserialize_number_from_string")]
    pub nonce: i32,
    #[serde(default)]
    pub has_error_in_internal_transactions: Option<bool>,

    pub actions: Vec<models::TransactionAction>,
    #[serde(default)]
    pub decoded_input: Option<models::DecodedInput>,

    #[serde(default)]
    pub token_transfers_overflow: Option<bool>,

    pub raw_input: String,
    pub value: String,
    #[serde(default)]
    pub max_priority_fee_per_gas: Option<String>,

    #[serde(default)]
    pub revert_reason: Option<serde_json::Value>,

    pub confirmation_duration: serde_json::Value,
    #[serde(default)]
    pub transaction_tag: Option<String>,
}
