/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionSummary {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "data")]
    pub data: models::TransactionSummaryObj,
}

impl TransactionSummary {
    pub fn new(success: bool, data: models::TransactionSummaryObj) -> TransactionSummary {
        TransactionSummary { success, data }
    }
}
