/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct V1CelestiaL2BatchMetadata {
    // isNullable = false
    // required = false
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    pub l2_chain_id: 
    Option<


            
            i64

    >,
    // isNullable = false
    // required = false
    
    pub l2_batch_id: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub l2_start_block: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub l2_end_block: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    pub l2_batch_tx_count: 
    Option<


            
            i64

    >,
    // isNullable = false
    // required = false
    
    pub l2_blockscout_url: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub l1_tx_hash: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    
    pub l1_tx_timestamp: 
    Option<


            
            String

    >,
    // isNullable = false
    // required = false
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    pub l1_chain_id: 
    Option<


            
            i64

    >,
    // isNullable = false
    // required = false
    
    pub related_blobs: 
    Option<


            
            Vec<models::V1CelestiaBlobId>

    >,
}



