/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Data {
    #[serde(
        rename = "cache_latest_block_inserted_at",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_latest_block_inserted_at: Option<String>,
    #[serde(
        rename = "cache_latest_block_number",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_latest_block_number: Option<String>,
    #[serde(
        rename = "latest_block_inserted_at",
        skip_serializing_if = "Option::is_none"
    )]
    pub latest_block_inserted_at: Option<String>,
    #[serde(
        rename = "latest_block_number",
        skip_serializing_if = "Option::is_none"
    )]
    pub latest_block_number: Option<String>,
}

impl V1Data {
    pub fn new() -> V1Data {
        V1Data {
            cache_latest_block_inserted_at: None,
            cache_latest_block_number: None,
            latest_block_inserted_at: None,
            latest_block_number: None,
        }
    }
}
