/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct V1EntryPointIndexerStatus {
    // isNullable = false
    // required = false
    
    pub enabled: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub live: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub past_db_logs_indexing_finished: 
    Option<


            
            bool

    >,
    // isNullable = false
    // required = false
    
    pub past_rpc_logs_indexing_finished: 
    Option<


            
            bool

    >,
}



