/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1IndexerStatus {
    #[serde(rename = "finished_past_indexing", skip_serializing_if = "Option::is_none")]
    pub finished_past_indexing: Option<bool>,
    #[serde(rename = "v06", skip_serializing_if = "Option::is_none")]
    pub v06: Option<models::V1EntryPointIndexerStatus>,
    #[serde(rename = "v07", skip_serializing_if = "Option::is_none")]
    pub v07: Option<models::V1EntryPointIndexerStatus>,
}

impl V1IndexerStatus {
    pub fn new() -> V1IndexerStatus {
        V1IndexerStatus {
            finished_past_indexing: None,
            v06: None,
            v07: None,
        }
    }
}

