/*
 * BlockScout API
 *
 * API for BlockScout web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lymarenko.lev@blockscout.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct Withdrawal {
    // isNullable = false
    // required = true
    #[serde(deserialize_with = "deserialize_number_from_string")]
    
    pub index: 
    


            
            i32

    ,
    // isNullable = false
    // required = true
    
    pub amount: 
    


            
            String

    ,
    // isNullable = false
    // required = true
    #[serde(deserialize_with = "deserialize_number_from_string")]
    
    pub validator_index: 
    


            
            i32

    ,
    // isNullable = false
    // required = false
    
    pub receiver: 
    Option<


            
            models::AddressParam
            

    >,
    // isNullable = false
    // required = false
    #[serde(default, deserialize_with = "deserialize_option_number_from_string")]
    
    pub block_number: 
    Option<


            
            i32

    >,
    // isNullable = false
    // required = false
    
    pub timestamp: 
    Option<


            
            String

    >,
}



