/*

* BlockScout API
*


* API for BlockScout web app
*

* The version of the OpenAPI document: 1.0.0
* Contact: lymarenko.lev@blockscout.com
* Generated by: https://openapi-generator.tech
*/

use crate::models;
use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, derive_new::new)]
pub struct Withdrawal {
    pub index: i32,
    pub amount: String,
    pub validator_index: i32,
    #[serde(default)]
    pub receiver: Option<models::AddressParam>,

    #[serde(default)]
    pub block_number: Option<i32>,

    #[serde(default)]
    pub timestamp: Option<String>,
}
